// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoqvV-QWLfxBU7wD3YxjQv-essbSQTxzQ',
    appId: '1:349030483442:web:03055cd60d9b4b9c1c576b',
    messagingSenderId: '349030483442',
    projectId: 'hrmanagementsystem-3893d',
    authDomain: 'hrmanagementsystem-3893d.firebaseapp.com',
    storageBucket: 'hrmanagementsystem-3893d.appspot.com',
    measurementId: 'G-7CY3LGSDYP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCAqoh337S71soOOKCf54yojs9YigOuDc',
    appId: '1:349030483442:android:122eebae7407a84d1c576b',
    messagingSenderId: '349030483442',
    projectId: 'hrmanagementsystem-3893d',
    storageBucket: 'hrmanagementsystem-3893d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtp7T8R5WDm_5wjlxtFClr9PxY4OmRe-A',
    appId: '1:349030483442:ios:d4327ff483235df01c576b',
    messagingSenderId: '349030483442',
    projectId: 'hrmanagementsystem-3893d',
    storageBucket: 'hrmanagementsystem-3893d.appspot.com',
    iosBundleId: 'com.example.inxeeHrApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtp7T8R5WDm_5wjlxtFClr9PxY4OmRe-A',
    appId: '1:349030483442:ios:d4327ff483235df01c576b',
    messagingSenderId: '349030483442',
    projectId: 'hrmanagementsystem-3893d',
    storageBucket: 'hrmanagementsystem-3893d.appspot.com',
    iosBundleId: 'com.example.inxeeHrApplication',
  );
}
